### ISSUE TITLE
Public Instance Dead

### ISSUE THREAD

**Issue by macbrayne** [mikbot/regenbogen-ice#38]
The public instance of the bot currently doesn't seem to work, is that planned / did you stop hosting the bot?

**Comment by NyCodeGHG** [comment]
I had a few issues with it, it should be back now :)

**Comment by NyCodeGHG** [comment]
There seems to be a critical bug and the code does not compile anymore because of a breaking dependency change

**Comment by DRSchlaubi** [comment]
breaking dependency changes have been resolved
